version: "3"
services:
  db:
    image: "mysql:latest"
  client:
    build: ./wow-tracker-client
    ports:
      - "3000:3000"
  server:
    build: ./wow-tracker-server
    ports:
      - "4000:4000"
