version: "3"
services:
  db:
    image: "ops3199/wow-db:latest"
    ports:
      - "3306:3306"
  client:
    platform: linux/amd64
    build: ./wow-tracker-client
    ports:
      - "3000:3000"
  server:
    platform: linux/amd64
    build: ./wow-tracker-server
    ports:
      - "4000:4000"
